PRODUCT_VERSION_MAJOR := 13
PRODUCT_VERSION_MINOR := 0
PRODUCT_VERSION_TAG := Solar

TARGET_PRODUCT_SHORT := $(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)
FIELD_HOST_TIME := $(shell date -u +%Y%m%d-%H%M%S)

FIELD_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(PRODUCT_VERSION_TAG)

FIELD_BUILD_VARIANT ?= COMMUNITY

FIELD_BUILD := FieldOS-$(FIELD_VERSION)-$(TARGET_PRODUCT_SHORT)-$(FIELD_BUILD_VARIANT)-Vanilla-$(FIELD_HOST_TIME)
ifeq ($(WITH_GAPPS), true)
FIELD_BUILD := FieldOS-$(FIELD_VERSION)-$(TARGET_PRODUCT_SHORT)-$(FIELD_BUILD_VARIANT)-$(FIELD_HOST_TIME)
endif
RELEASE_TYPE := $(FIELD_BUILD_VARIANT)
